### ISSUE TITLE
working with pagination

### ISSUE THREAD

**Issue by cilindrox** [aptible/go-deploy#1]
Hi there, I'm running into some issues trying to use the API client to fetch an account's apps and paginate through results.

Following the usage example under `main.go`:

```go
	page := int64(1)
	params := operations.NewGetAppsParams().WithPage(&page)
	resp, err := client.Operations.GetApps(params, bearerTokenAuth)
	if err != nil {
		return []string{}, err
	}

	log.Printf("> TOTAL PAGES %d - Current %d - Per Page %d", resp.Payload.TotalCount, resp.Payload.CurrentPage, resp.Payload.PerPage)
```

My idea was to leverage `Payload.TotalCount` and `Payload.PerPage` to iterate across apps for a given account, but I'm getting some weird numbers, eg:

```
> TOTAL PAGES 824637552320 - Current 824637552384 - Per Page 824637552352
```

Those _kinda_ make sense, but it's not as straightforward as I thought, eg:

Current - Total = actual total number of apps
Per Page - Total = actual per page numbers

Finally, current/per page yields the actual amount of apps for the account, but all of this seems like I'm doing things _really wrong_ - is there a more straightforward way of paginating through the results that I'm not seeing?

**Comment by robertfairhead** [comment]
Hey @cilindrox! This repo is still VERY alpha and under heavy development so it's not ready for general use yet. We expect significant breaking changes to occur with no notice. Therefore, we don't suggest any use of it at this point. This repo was only made public now to simplify some tooling issues in our CI/CD.

I will update the README to make it much clearer that this is not ready yet. We do expect to stabilize this project at some point and will be cutting SEMVER releases (in line with general Go modules practices) once that is the case. Any use before we officially release of it beta is risky.

For your specific question on pagination, we are still experimenting with appropriate approaches there so I don't have a firm answer to give you on the best way to approach it. To clarify a little, the values you're printing for `resp.Payload.TotalCount`, `resp.Payload.CurrentPage`, and `resp.Payload.PerPage` are of type `*int64` so you may want to use a helper function like https://godoc.org/github.com/AlekSi/pointer#GetInt64 to get the "real" value you're looking for there. You can either do the math to see if total - current > 0 or you can check for the `resp.Payload.Links.Next` being non-nil to know if you need to page. We intend to include some pagination support in the future.

I do want to reiterate this though, that you **should not** use this for **anything** that would interact with your production resources as it is known buggy still and doing so may cause unexpected impacts on your resources.

**Comment by cilindrox** [comment]
Thanks @robertfairhead for the insight - and yes, was aware of the unstable nature of this, just playing around to start planning a way ahead :)

Thanks for putting this together again, this is a huge help for things like terraform and custom pipelines/tooling.
